import {
  BITVAVO_SYNC_JOB_ASSET_DATA,
  BITVAVO_SYNC_JOB_CANDLES_EUR,
  BITVAVO_SYNC_JOB_MARKETS_EUR,
  COINGECKO_SYNC_JOB_COIN_ID,
  COINGECKO_SYNC_JOB_METRICS,
  SYNC_JOB_EXECUTOR_CATALOG_CLOSE,
  SYNC_JOB_MEDIATOR_CATALOG_CLOSE,
  SYNC_JOB_SIGNALS_CATALOG_CLOSE,
} from "@/lib/agents/ingest/services/bitvavo-sync-status-record.service";

/** `sync_runs.job_key` values shown on the dashboard sync runs list and detail pages. */
export const SYNC_RUN_DASHBOARD_JOB_KEYS = [
  BITVAVO_SYNC_JOB_MARKETS_EUR,
  BITVAVO_SYNC_JOB_ASSET_DATA,
  BITVAVO_SYNC_JOB_CANDLES_EUR,
  COINGECKO_SYNC_JOB_METRICS,
  COINGECKO_SYNC_JOB_COIN_ID,
  SYNC_JOB_SIGNALS_CATALOG_CLOSE,
  SYNC_JOB_MEDIATOR_CATALOG_CLOSE,
  SYNC_JOB_EXECUTOR_CATALOG_CLOSE,
] as const;

export type SyncRunDashboardJobKey = (typeof SYNC_RUN_DASHBOARD_JOB_KEYS)[number];
